--比较线程标识和锁中的标识是否一致
if(redis.call("get",KEYS[1]) == ARGV[1]) then
    return redis.call("del",KEYS[1])
end
    return 0

--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2026/5/7 17:21
---